
#ifndef GEOGRAM_BASIC_VERSION
#define GEOGRAM_BASIC_VERSION

#define VORPALINE_VERSION_MAJOR "1"
#define VORPALINE_VERSION_MINOR "6"
#define VORPALINE_VERSION_PATCH "8"
#define VORPALINE_VERSION "1.6.8"
#define VORPALINE_BUILD_NUMBER ""
#define VORPALINE_BUILD_DATE "2020-01-14 17:19:56"
#define VORPALINE_SVN_REVISION ""

#endif

